apiVersion: v1
kind: Pod
metadata:
  name: centos7-pod
spec:
  containers:
  - name: centos7
    image: centos:7
    command: ["/bin/bash","-c","while true; do sleep 1000; done"]
    imagePullPolicy: IfNotPresent