apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
spec:
  nodeName: 
  containers:
  - name: iperf3-server
    image: centos:7
    command: ["/bin/bash","-c","while true; do sleep 1000; done"]
    imagePullPolicy: IfNotPresent